version: '3.8'

services:
  # .NET Application Service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: academia-novit-web
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=academianovitdb;Username=postgres;Password=postgres123
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: academia-novit-db
    environment:
      POSTGRES_DB: academianovitdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  postgres_data: