version: '3.8'

services:
  # .NET Application Service
  web:
    image: ${DOCKERHUB_USERNAME}/academianovit:latest
    container_name: academia-novit-web
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=academianovitdb;Username=postgres;Password=postgres123
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: academia-novit-db
    environment:
      POSTGRES_DB: academianovitdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  postgres_data: