name: Build and Push to Docker Hub

on:
  push:
    branches: ["develop"]
    paths:
      - "AcademiaNovit/**"
      - "Dockerfile"
      - ".github/workflows/GH-docker-registry-DEV.yml"
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag (e.g., v1.0.0)"
        required: true
        default: "latest"

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          # Disable all caching
          no-cache: true

      - name: Verify image push
        run: |
          echo "Successfully pushed ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop"
