name: Build and Push to Docker Hub

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'AcademiaNovit/**'
      - 'Dockerfile'
      - '.github/workflows/GH-docker-registry-DEV.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag para la imagen (ej: v1.0.0)'
        required: true
        default: 'latest'

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=develop,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=ghac,mode=max

      - name: Image digest
        run: echo ${{ steps.meta.outputs.tags }}
